# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='Testtesttest', max_length=300),
        ),
    ]
